version: '3'

services:

  #? ==================================
  #? NATS SERVER
  #? ==================================

  nats-server:
    image: nats:latest


  #? ==================================
  #? CLIENT GATEWAY
  #? ==================================

  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: client-gateway-prod
    # ports:
    #   - '${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}'
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  #? ==================================
  #? PRODUCTS MICROSERVICE
  #? ==================================

  products-microservices:
    build: 
      context: ./products-microservices
      dockerfile: dockerfile.prod
    image: products-microservices-prod
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  #? ==================================
  #? ORDERS MICROSERVICE
  #? ==================================

  orders-microservices:
    build: 
      context: ./orders-microservices
      dockerfile: dockerfile.prod
      args:
        ORDERS_DATABASE_URL: ${ORDERS_DATABASE_URL}
    image: orders-microservices-prod
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}

  orders-db:
    container_name: orders-database
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-microservices/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ordersdb

  #? ==================================
  #? AUTH MICROSERVICE
  #? ==================================
  auth-microservices:
    build: 
      context: ./auth-microservices
      dockerfile: dockerfile.prod
    image: auth-microservices-prod
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  #? ==================================
  #? PAYMENTS MICROSERVICE
  #? ==================================
  payments-microservices:
    container_name: payments-microservices
    build: 
      context: ./payments-microservices
      dockerfile: dockerfile.prod
    image: payments-microservices-prod
    ports:
      - ${PAYMENTS_MICROSERVICES_PORT}:${PAYMENTS_MICROSERVICES_PORT}
    environment:
      - PORT=${PAYMENTS_MICROSERVICES_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}

