apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-microservice
  name: payments-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-microservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-microservice
    spec:
      containers:
      - image: us-west1-docker.pkg.dev/microservices-store-419406/image-registry/payments-microservice
        name: payments-microservice
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: STRIPE_SUCCESS_URL
          value: "http://localhost:3003/payments/success"
        - name: STRIPE_CANCEL_URL
          value: "http://localhost:3003/payments/cancel"
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe-secret-key
        - name: STRIPE_ENDPOINT_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe-endpoint-secret
        resources: {}
status: {}
